### ISSUE TITLE
helm-build-sync-source not being found

### ISSUE THREAD

**Issue by kylev** [vspinu/imenu-anywhere#26]
I'm working on figuring out bbatsov/prelude#964, and it appears that c01f018c9fa44ccc927be852f7efdb170adc1895 may have broken things. In my current helm from melpa (20160126.1110), the `helm-build-sync-source` macro is found in helm-core, not helm-source, so your autoload fails.

**Comment by kylev** [comment]
Yeah, [based on this](https://github.com/emacs-helm/helm#install-and-use-only-helm-core-package), I think your autoload statement should be to load from `helm-core`. It's the package name rather than the source file name.

**Comment by syohex** [comment]
> Yeah, based on this, I think your autoload statement should be to load from helm-core. It's the package name rather than the source file name.

No. It should be file name. Please see `autoload` document. If it is not existed file, then error may be raised at runtime.

**Comment by syohex** [comment]
When a macro is passed to `autoload` function, fifth argument has to be set `t` or `'macro`. Please see `autoload` document.

However I suppose it is not good to use `autoload`. Because all users must install helm for using `imenu-anywhere`, even if users does not use helm. Emacs expands macro at byte-compiling time and load helm by autoload setting. If users does not install helm, then byte-compile is failed.

**Comment by kylev** [comment]
Or perhaps in the short term, the after-load hook around `defvar helm-source-imenu-anywhere` should run after load of `helm-core`, which is where `helm-sources` is packaged?

**Comment by syohex** [comment]
> Or perhaps in the short term, the after-load hook around defvar helm-source-imenu-anywhere should run after load of helm-core, which is where helm-sources is packaged?

https://github.com/emacs-helm/helm/blob/master/helm-source.el

It is part of `helm-core`. And helm-core is package name, not file name. Body of that eval-after-load is evaluated after loading helm.el.

NOTE Emacs also byte-compiles body of eval-after-load. Emacs does not know what helm-build-sync-source is, a function or a macro if helm.el is not loaded. So Emacs byte-compiles it as function and error is raised at runtime because it is a macro, not function.

**Comment by vspinu** [comment]
Ok. For now I am declaring them as macros. That should fix it. Whatever way I go, be it `autload` or `declare-function` byte-compilation fails without helm. That's not good. 

Best solotion would be, as  @syohex proposed, to get helm component into helm-imenu-anywhere.

@syohex, is there a way to achieve this without bothering existing helm-imenu-anywhere users?

**Comment by syohex** [comment]
Hmm, it is difficult...

**Comment by syohex** [comment]
> is there a way to achieve this without bothering existing helm-imenu-anywhere users? 

I suppose there is no effect for users who uses package manager like package.el. There is no `:files` attribute in [MELPA recipe](https://github.com/milkypostman/melpa/blob/master/recipes/imenu-anywhere) and MELPA uses `:defaults` which is following rule. So MELPA packages both imenu-anywhere.el and helm-imenu-anywhere.el without changing recipe if helm code is moved to another file.

```
("*.el" "*.el.in" "dir"
 "*.info" "*.texi" "*.texinfo"
 "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
 (:exclude ".dir-locals.el" "test.el" "tests.el" "*-test.el" "*-tests.el"))
```

Users who install this package manually may confuse, however such users is minority now.
