### ISSUE TITLE
Possible to formate the look to match counsel-menu?

### ISSUE THREAD

**Issue by dunkarooftop** [vspinu/imenu-anywhere#39]
Here is what counsel-menu looks like with prettier formatting
https://i.imgur.com/foaKwxI.png

compare to  ivy-imenu-everywhere
https://i.imgur.com/uulTn3d.png

I would love to match the look :)

thanks for the great work !!

**Comment by vspinu** [comment]
Do I understand correctly that the difference is that in counsel candidates appear in the same order as in the buffer and the closest match is highlighted? Then how would you sort candidates from the other buffers for `imenu-anywhere`? 

If you can find an elegant solution (no copy paste of counsel's code) I would be more than happy to accept a PR for `counsel-imenu-anywhere`. I am unlikely to investigate it myself because I am not an ivy/counsel guy.

**Comment by dunkarooftop** [comment]
All good I will need to brush up my emacs-lisp skill 1st haha :)
